import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const myLoader = ({ src, width, quality }) => {
  console.log(quality);
  if (quality) {
    return ` https://d2ehgcmlo5u3sg.cloudfront.net${src}?format=auto&quality=${quality}&width=${width}`;
  } else
    return ` https://d2ehgcmlo5u3sg.cloudfront.net${src}?format=auto&width=${width}`;
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App with optimized images</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>The official website of Rio</h1>
        <p className={styles.description}>
          {" "}
          All animals are equal but some are more equal than others — Orwell
        </p>{" "}
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>The look</h2>
            <p>When Rio wants to ask you for something</p>
            <br />
            <Image
              src="/images/rio/4.jpeg"
              loader={myLoader}
              layout="responsive"
              sizes="20vw"
              width={900}
              height={1200}
            />{" "}
          </div>
          <div className={styles.card}>
            <h2>New encounters</h2>
            <p>When Rio meets a goose for the first time</p>
            <br />
            <Image
              src="/images/rio/3.jpeg"
              loader={myLoader}
              layout="responsive"
              sizes="20vw"
              width={900}
              height={1200}
            />{" "}
          </div>
          <div className={styles.card}>
            <h2>Happiness</h2>
            <p>When Rio goes to play at the beach</p>
            <br />
            <Image
              src="/images/rio/1.jpeg"
              loader={myLoader}
              layout="responsive"
              sizes="20vw"
              width={900}
              height={1200}
            />{" "}
          </div>
          <div className={styles.card}>
            <h2>In love</h2>
            <p>When Rio falls in love.. with Flo the neighboor dog</p>
            <br />
            <Image
              src="/images/rio/2.jpeg"
              loader={myLoader}
              layout="responsive"
              sizes="20vw"
              width={900}
              height={1200}
            />{" "}
          </div>
        </div>
      </main>
    </div>
  );
}
